export const APP_NAME = "Zuz";
export const APP_DESCRIPTION = "Nextjs Boilerplate";
export const APP_URL = "http://www.zuz.com.pk/"
export const VERSION = `2.0.1`;
export const SESS_KEYS = ['ui','ut','ud','si'];
export const SESS_PREFIX = `__`;
export const SECURE_KEY = "ADD_YOUR_SECURE_KEY_HERE"
export const GA_MEASUREMENT_ID = "__";
export const ADMIN_EMAIL = `hello@zuz.com.pk`;